export enum TransactionState {
  CREATED = "CREATED",
  ROUTING = "ROUTING",
  PROCESSING = "PROCESSING",
  SUCCESS = "SUCCESS",
  FAILED = "FAILED",
  RETRYING = "RETRYING",
  FAILED_FINAL = "FAILED_FINAL",
}